create table `gene_feature`(
`gene_no` int not null,
`gene_id` char(30),
`ARO` int,
`AUS` int, 
`ADM` int, 
`ind1` int, 
`ind2` int, 
`ind3` int, 
`ind4` int, 
`ind5` int, 
`jap1` int, 
`jap2` int, 
`jap3` int, 
`jap4` int, 
`JAP` int, 
`IND` int, 
`ALL` int, 
`Age` char(7), 
`P_JAP` float(7,4), 
`P_IND` float(7,4), 
`P_ARO` float(7,4), 
`P_AUS` float(7,4), 
`P_ADM` float(7,4), 
`CoreFlag` tinyint, 
`SP_IND` tinyint, 
`SP_JAP` tinyint, 
`SP_AUS` tinyint, 
`SP_ARO` tinyint, 
`P_ind1` float(7,4), 
`P_ind2` float(7,4), 
`P_ind3` float(7,4), 
`P_ind4` float(7,4), 
`P_ind5` float(7,4), 
`P_jap1` float(7,4), 
`P_jap2` float(7,4), 
`P_jap3` float(7,4), 
`P_jap4` float(7,4), 
`GroupDependent_flag` tinyint, 
`GroupDependent_flagX` tinyint, 
`GroupDependent_flagG` tinyint, 
`IndDependent_flag` tinyint, 
`JapDependent_flag` tinyint, 
`subgroup_dominant` tinyint, 
`random_flag` tinyint,
`canCore_flag` tinyint,
key `gene_no` (`gene_no`),
key `gene_id` (`gene_id`),
CONSTRAINT `gene_feature_ibfk_1` FOREIGN KEY (`gene_no`) REFERENCES `gene_info` (`gene_no`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;